apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gcd-deployment
  labels:
    app: gcd
spec:
  selector:
    matchLabels:
      app: gcd
  replicas: 3
  revisionHistoryLimit: 5
  strategy:
      type: RollingUpdate
      rollingUpdate:
          maxSurge: 1
          maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: gcd
    spec:
      containers:
      - name: gcd
        image: yangwen13/gcd:0.1
        imagePullPolicy: Always
        ports:
        - name: gcd-service
          containerPort: 3000
        env:
            - name: FOR_GODS_SAKE_PLEASE_REDEPLOY
              value: '2'

---

apiVersion: v1
kind: Service
metadata:
  name: gcd-service
spec:
  selector:
    app: gcd
  ports:
  - port: 3000
    targetPort: gcd-service
  type: LoadBalancer
