apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name.service: my-mongodb
  name: my-mongodb
spec:
  type: NodePort
  ports:
  - name: "27100"
    port: 27100
    targetPort: 27100
    nodePort: 30001
  selector:
    name.service: my-mongodb
status:
  {}