apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webappgo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webappgo
        tier: frontend
    spec:
      containers:
      - name: webappgo
        image: webappgo:v1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        imagePullPolicy: IfNotPresent
      containers:
      - name: webserver
        image: nginx:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80